baseURL = 'https://francescobux.com'
languageCode = 'en-us'
title = 'Francesco Bux - Portfolio Website'
theme = 'creative-portfolio'

# Enable comments by entering your Disqus shortname
disqusShortname = ""
# Enable Google Analytics by entering your tracking code
googleAnalytics = "G-J3M4VCLVR1"


[params]
  # Style options: default (pink), blue, green, pink, red, sea, violet
  # Use custom.css for your custom styling
  style = "blue"
  description = "Fractional CTO, Data/SW/AI Engineer, and Founder with extensive experience building innovative platforms for startups, scale-ups, and corporates. Currently Head of Data at Tebi, ex-Meta, with expertise in software/cloud/data/ML engineering and technical leadership"

  personalImage = "![targets](/img/my_linkedin.jpeg)"

  copyright = "&copy;2024 Francesco @ Octosoft"
  sidebarAbout = [
    "Fractional CTO and Head of Data at Tebi (ex-Meta). I specialize in building scalable platforms across software, cloud, data, and ML engineering. Based in Amsterdam, I help startups and scale-ups turn ideas into reality."
  ]
  # Contact page
     # Since this template is static, the contact form uses www.formspree.io as a
     # proxy. The form makes a POST request to their servers to send the actual
     # email. Visitors can send up to a 1000 emails each month for free.
     #
     # What you need to do for the setup?
     #
     # - set your email address under 'email' below
     # - upload the generated site to your server
     # - send a dummy email yourself to confirm your account
     # - click the confirm link in the email from www.formspree.io
     # - you're done. Happy mailing!
  email = "f/xnqkrwnw"

    # Optional Matomo analytics (formerly piwik)
      # [params.analytics.matomo]
      #  URL = "https://stats.example.com"
      #  ID = "42"
      #  # Track all subdomains with "*.example.com" (Optional)
      #  domain = "www.example.com"
      #  # Optional integrity check hash
      #  hash = ""

  # Nav links in the side bar
  [[params.navlinks]]
  name = "Home"
  url = "portfolio/"
  home = true

  [[params.navlinks]]
  name = "Discuss a project"
  url = "https://calendar.google.com/calendar/u/0/appointments/AcZssZ2DZzkiKiYy8PdxfR2tVgE3NrOjvmE4jBEIz-U="

  [[params.navlinks]]
  name = "Get in touch"
  url = "contact/"

  [params.social]
  email         = "francesco[at]octosoft.it"
  linkedin      = "www.linkedin.com/in/francescobux"
  github        = "https://github.com/sh1n"
  whatsapp      = "https://api.whatsapp.com/send?phone=31683265586&text=Hi%20Francesco%2C%20I%20would%20like%20to%20discuss%20a%20project%20with%20you!"

